name = "TypedFASTX"
uuid = "6c3c8c82-ef46-460a-9a5a-30cbd93ae9ab"
authors = ["Anton Sollman <anton.sollman@outlook.com>"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
