name = "TypedFASTX"
uuid = "6c3c8c82-ef46-460a-9a5a-30cbd93ae9ab"
authors = ["Anton Sollman <anton.sollman@outlook.com>"]
version = "0.1.1"

[deps]
FASTX = "c2308a5c-f048-11e8-3e8a-31650f418d12"
BioSequences = "7e6ae17a-c86d-528c-b3b9-7f778a29fe59"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
julia = "^1.6"
FASTX = "^2.1.2"
BioSequences = "^3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
