name = "TypedFASTX"
uuid = "6c3c8c82-ef46-460a-9a5a-30cbd93ae9ab"
authors = ["Anton Sollman <anton.sollman@outlook.com>"]
version = "0.4.3"

[deps]
BioSequences = "7e6ae17a-c86d-528c-b3b9-7f778a29fe59"
FASTX = "c2308a5c-f048-11e8-3e8a-31650f418d12"

[compat]
BioSequences = "^3"
FASTX = "^2"
julia = "^1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"

[targets]
test = ["Test", "Logging"]
